name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: ['*']

jobs:
  macos:
    name: build
    runs-on: macos-13
    env:
      DEVELOPER_DIR: /Applications/Xcode_15.0.app/Contents/Developer

    steps:
      - name: Checkout steamworks SDK
        uses: actions/checkout@v3
        with:
          repository: johnfairh/steamworks-swift-sdk
          path: steamworks-sdk

      - name: Checkout spacewar
        uses: actions/checkout@v3
        with:
          path: spacewar

      - name: Build
        run: |
          cd steamworks-sdk && make install && cd ..
          cd spacewar && swift build
