name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: ['*']

jobs:
  macos:
    name: build
    runs-on: macos-14
    steps:
      - name: Checkout steamworks SDK
        uses: actions/checkout@v4
        with:
          repository: johnfairh/steamworks-swift-sdk
          path: steamworks-sdk
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '16.0-beta'

      - name: Checkout spacewar
        uses: actions/checkout@v3
        with:
          path: spacewar

      - name: Build
        run: |
          cd steamworks-sdk && sudo make install && cd ..
          cd spacewar && swift build
